# Nome da aplicação
spring.application.name=crud-filmes

# Porta da API
server.port=8080

# Banco de dados H2 em memória (nao precisa instalar nada)
spring.datasource.url=jdbc:h2:mem:filmesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console web do H2 -> acessivel em http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cria/atualiza as tabelas automaticamente com base nas entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
